version: '3.8'

services:
  huggingface_env:
    container_name: huggingface_container
    image: huggingface_env
    build: .
    hostname: huggingface
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    command:
      [
        "/bin/bash",
        "-c",
        "trap : TERM INT; sleep infinity & wait"
      ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
